// <auto-generated />
using UrduMeaning.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace UrduMeaning.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602000000_AddCorrectionDefinitionSnapshot")]
    partial class AddCorrectionDefinitionSnapshot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);
        }
    }
}
