# =============================================================================
# scripts/populate_approved_words_from_bulk.ps1
#
# Loads approved_words from scripts/words/processed/word_queue_bulk.sql without
# using word_queue as the permanent validity source.
#
# The bulk SQL file is generated by process_word_list.ps1 and is gitignored
# because it is large. This script extracts ('word', priority) tuples, creates a
# compact temp SQL file, and loads it into local Docker Postgres by default.
# =============================================================================

param(
    [string]$BulkSql = (Join-Path $PSScriptRoot "words\processed\word_queue_bulk.sql"),
    [string]$OutputSql = (Join-Path $PSScriptRoot "words\processed\approved_words_bulk.sql"),
    [switch]$LoadToDb
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $BulkSql)) {
    Write-Host "Bulk SQL not found: $BulkSql" -ForegroundColor Red
    Write-Host "Generate it with: .\scripts\process_word_list.ps1 -OutputSql" -ForegroundColor Yellow
    exit 1
}

$outDir = Split-Path $OutputSql -Parent
if (-not (Test-Path $outDir)) {
    New-Item -ItemType Directory -Path $outDir -Force | Out-Null
}

$rx = [regex]"^\s*\('([^']+)',\s*([1-5])\),?"
$seen = [System.Collections.Generic.Dictionary[string, int]]::new([System.StringComparer]::OrdinalIgnoreCase)

Write-Host "Reading $BulkSql ..." -ForegroundColor Gray
foreach ($line in [System.IO.File]::ReadLines($BulkSql)) {
    $match = $rx.Match($line)
    if (-not $match.Success) { continue }

    $word = $match.Groups[1].Value.Trim().ToLowerInvariant()
    $priority = [int]$match.Groups[2].Value
    if ($word -eq "") { continue }

    if ($seen.ContainsKey($word)) {
        if ($priority -lt $seen[$word]) { $seen[$word] = $priority }
    } else {
        $seen.Add($word, $priority)
    }
}

Write-Host "Extracted $($seen.Count) approved words." -ForegroundColor Green

$writer = [System.IO.StreamWriter]::new($OutputSql, $false, [System.Text.UTF8Encoding]::new($false))
try {
    $writer.WriteLine("-- Generated by scripts/populate_approved_words_from_bulk.ps1")
    $writer.WriteLine("-- Source: $BulkSql")
    $writer.WriteLine("-- Words: $($seen.Count)")
    $writer.WriteLine("")
    $writer.WriteLine("CREATE TABLE IF NOT EXISTS approved_words (")
    $writer.WriteLine("    word text PRIMARY KEY,")
    $writer.WriteLine("    source text NOT NULL DEFAULT 'manual',")
    $writer.WriteLine("    priority integer NOT NULL DEFAULT 3,")
    $writer.WriteLine("    created_at timestamptz NOT NULL DEFAULT now()")
    $writer.WriteLine(");")
    $writer.WriteLine("")
    $writer.WriteLine("CREATE INDEX IF NOT EXISTS idx_approved_words_priority ON approved_words(priority);")
    $writer.WriteLine("")
    $writer.WriteLine("CREATE TEMP TABLE _approved_stage (word text, priority int) ON COMMIT DROP;")
    $writer.WriteLine("")

    $items = $seen.GetEnumerator() | Sort-Object Value, Key
    $batchSize = 5000
    for ($i = 0; $i -lt $items.Count; $i += $batchSize) {
        $end = [Math]::Min($i + $batchSize - 1, $items.Count - 1)
        $writer.WriteLine("INSERT INTO _approved_stage (word, priority) VALUES")
        for ($j = $i; $j -le $end; $j++) {
            $escaped = $items[$j].Key -replace "'", "''"
            $comma = if ($j -lt $end) { "," } else { ";" }
            $writer.WriteLine("  ('$escaped', $($items[$j].Value))$comma")
        }
        $writer.WriteLine("")
    }

    $writer.WriteLine("INSERT INTO approved_words (word, source, priority)")
    $writer.WriteLine("SELECT word, 'bulk_word_list', min(priority)")
    $writer.WriteLine("FROM _approved_stage")
    $writer.WriteLine("GROUP BY word")
    $writer.WriteLine("ON CONFLICT (word) DO UPDATE")
    $writer.WriteLine("SET priority = LEAST(approved_words.priority, EXCLUDED.priority);")
    $writer.WriteLine("")
    $writer.WriteLine("SELECT priority, count(*) AS approved_count FROM approved_words GROUP BY priority ORDER BY priority;")
}
finally {
    $writer.Close()
}

Write-Host "Wrote $OutputSql" -ForegroundColor Green

if ($LoadToDb) {
    Write-Host "Loading into local Docker Postgres..." -ForegroundColor Gray
    Get-Content $OutputSql | docker compose exec -T postgres psql -U postgres -d lughatai
    Write-Host "Done." -ForegroundColor Green
} else {
    Write-Host "To load locally:" -ForegroundColor Cyan
    Write-Host "  Get-Content `"$OutputSql`" | docker compose exec -T postgres psql -U postgres -d lughatai" -ForegroundColor White
}
