import type { Metadata } from "next";
import Link from "next/link";
import { SITE_NAME, SITE_URL } from "@/lib/site";

export const metadata: Metadata = {
  title: `Terms of Service | ${SITE_NAME}`,
  description: "Terms of service for UrduMeaning — acceptable use, disclaimers, and governing law.",
  alternates: { canonical: `${SITE_URL}/terms` },
};

export default function TermsPage() {
  return (
    <main className="mx-auto max-w-2xl px-4 py-12 md:py-16">
      <h1 className="text-3xl font-bold tracking-tight text-gray-900 dark:text-gray-100 mb-2">
        Terms of Service
      </h1>
      <p className="text-sm text-gray-500 dark:text-gray-400 mb-10">
        Effective date: 24 May 2026 &nbsp;·&nbsp; ThetaFoundry LLC
      </p>

      <div className="space-y-10 text-gray-700 dark:text-gray-300 leading-relaxed">
        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
            1. Acceptance
          </h2>
          <p>
            By using urdumeaning.com (&ldquo;the Service&rdquo;), you agree to
            these Terms of Service. If you do not agree, please do not use the
            Service. The Service is operated by ThetaFoundry LLC
            (&ldquo;we&rdquo;, &ldquo;our&rdquo;, &ldquo;us&rdquo;).
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
            2. Description of service
          </h2>
          <p>
            UrduMeaning provides an AI-assisted English-to-Urdu dictionary. Word
            definitions are generated by large language models and stored in our
            database. The Service is provided free of charge and is subject to
            change at any time.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
            3. AI-generated content disclaimer
          </h2>
          <p>
            Definitions, translations, examples, poetry, and other content on
            this site are generated by artificial intelligence and may contain
            errors, inaccuracies, or omissions. This content is provided for
            informational and educational purposes only. We do not guarantee the
            accuracy, completeness, or reliability of any AI-generated content.
            Do not rely solely on UrduMeaning for academic, legal, medical, or
            other professional purposes.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
            4. Acceptable use
          </h2>
          <p className="mb-3">You agree not to:</p>
          <ul className="list-disc list-inside space-y-2 ml-1">
            <li>
              Scrape, crawl, or systematically download content from the Service
              without prior written permission
            </li>
            <li>
              Use the Service in any way that could damage, disable, overburden,
              or impair our servers or networks
            </li>
            <li>
              Attempt to gain unauthorized access to any part of the Service or
              its infrastructure
            </li>
            <li>
              Use the Service for any unlawful purpose or in violation of any
              applicable laws or regulations
            </li>
            <li>
              Reproduce or redistribute content from the Service commercially
              without permission
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
            5. Intellectual property
          </h2>
          <p>
            The UrduMeaning name, logo, and site design are property of
            ThetaFoundry LLC. AI-generated definitions are produced on your
            behalf as a service and are not sold or licensed — they are provided
            for personal, non-commercial use. Classical poetry and proverbs
            reproduced on the site are historical works in the public domain.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
            6. Disclaimer of warranties
          </h2>
          <p>
            THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS
            AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED,
            INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS
            FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT. WE DO NOT WARRANT
            THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR FREE OF
            HARMFUL COMPONENTS.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
            7. Limitation of liability
          </h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, THETAFOUNDRY LLC SHALL NOT
            BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR
            PUNITIVE DAMAGES ARISING FROM YOUR USE OF, OR INABILITY TO USE, THE
            SERVICE.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
            8. Modifications
          </h2>
          <p>
            We reserve the right to modify or discontinue the Service at any
            time without notice. We may also update these Terms periodically.
            Continued use of the Service after changes constitutes acceptance of
            the updated Terms.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
            9. Governing law
          </h2>
          <p>
            These Terms are governed by the laws of the State of Delaware,
            United States, without regard to its conflict of law provisions. Any
            disputes shall be resolved in the courts of Delaware.
          </p>
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100 mb-3">
            10. Contact
          </h2>
          <p>
            Questions about these Terms?{" "}
            <Link
              href="/contact"
              className="text-indigo-600 dark:text-indigo-400 hover:underline"
            >
              Contact us
            </Link>
            .
          </p>
        </section>
      </div>
    </main>
  );
}
